version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/email_service
      - DB_USERNAME=postgres
      - DB_PASSWORD=vladp
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SERVER_PORT=8080
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=email_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vladp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 